# General
title: Dorrea
description: Dorrea gaztategiaren webgunea
author:
    name: Iune Trecet Obeso
    email: contact@iune.info
    github: iunetrecet
    web: http://iune.info
timezone: "Europe/Madrid"
theme: none


# Jekyll
exclude: [".rvmrc", ".rbenv-version", "Rakefile", "vendor"]
excerpt_separator: "\n"
markdown: kramdown
sass:
  sass_dir: _sass

collections:
  - products
  - farmers


# trans
t:
  eu:
    home: "Diseinu askeak<br/>kultura askearen alde."
